### ISSUE TITLE
Vidor 4000 distorted output when connected with VGA

### ISSUE THREAD

**Issue by oppaoppai** [FPGAArcade/replay_firmware#4]
I've encountered this issue when i tried to connect the vidor4000 to a VGA monitor.
I've set up the a chain composed by: micro hdmi -> hdmi -> vga -> monitor, the output results distorted.

It happens on every core, including the main menu.

![photo_2021-02-11_15-31-44](https://user-images.githubusercontent.com/35533749/107650018-57398a80-6c7e-11eb-8b18-89f6f96c5309.jpg)

**Comment by Takasa** [comment]
How are you doing the HDMI to VGA conversion? For questions you can also use the forum at www.fpgaarcade.com.
I'll set up a Vidor channel.

**Comment by oppaoppai** [comment]
I'm converting the HDMI to VGA with an active converter. Thanks for setting up the channel :)

**Comment by Takasa** [comment]
No worries. DM me on the forum and I'll send you a slack invite as well.
